import './globals.css'
import type { Metadata } from 'next'
import { Josefin_Sans } from 'next/font/google'

const josefin_Sans = Josefin_Sans({ 
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: {
    minimumScale: 1,
    initialScale: 1,
    width: 'device-width'
}
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head></head>
      <body className={josefin_Sans.className}>{children}</body>
    </html>
  )
}
